// SPDX-License-Identifier: Apache-2.0
#include "lshaz/hypothesis/ExperimentSynthesizer.h"

#include <llvm/Support/FileSystem.h>
#include <llvm/Support/Path.h>
#include <llvm/Support/raw_ostream.h>

#include <sstream>
#include <system_error>

namespace lshaz {

ExperimentFile ExperimentSynthesizer::generateCommonHeader(
    const LatencyHypothesis &hyp) {

    std::ostringstream os;
    os << "#pragma once\n"
       << "#define _GNU_SOURCE 1  /* sched_getcpu/affinity regardless of -std */\n"
       << "// Auto-generated by lshaz-experiment-synth\n"
       << "// Hypothesis: " << hyp.hypothesisId << "\n"
       << "// Hazard class: " << hazardClassName(hyp.hazardClass) << "\n"
       << "// Evidence tier: " << evidenceTierName(hyp.evidenceTier) << "\n\n"
       << "#include <cstdint>\n"
       << "#include <atomic>\n"
       << "#include <cstring>\n"
       << "#include <cstdio>\n"
       << "#include <cstdlib>\n"
       << "#include <fstream>\n"
       << "#include <set>\n"
       << "#include <string>\n"
       << "#include <thread>\n"
       << "#include <pthread.h>\n"
       << "#include <sched.h>\n"
       << "#include <unistd.h>\n\n"
       << "/* Anti-elision: prevent dead-code elimination of measured work. */\n"
       << "inline volatile uint64_t lshaz_global_sink;\n\n"
       << "template <typename T>\n"
       << "__attribute__((noinline)) void lshaz_do_not_optimize("
       << "T const& val) {\n"
       << "    asm volatile(\"\" : : \"r,m\"(val) : \"memory\");\n"
       << "}\n\n"
       << "inline __attribute__((noinline)) void lshaz_clobber_memory() {\n"
       << "    asm volatile(\"\" : : : \"memory\");\n"
       << "}\n\n"
       << "struct LatencySample {\n"
       << "    uint64_t tsc_start;\n"
       << "    uint64_t tsc_end;\n"
       << "};\n\n"
       << "static inline uint64_t lshaz_rdtsc() {\n"
       << "    uint64_t lo, hi;\n"
       << "    asm volatile(\"lfence; rdtsc; lfence\"\n"
       << "                 : \"=a\"(lo), \"=d\"(hi));\n"
       << "    return (hi << 32) | lo;\n"
       << "}\n\n"
       << "/* Contending writer on a sibling-distinct physical core. Without a\n"
       << "   second core mutating the co-located field there is no remote RFO,\n"
       << "   hence no false sharing to measure — a single-writer 'experiment'\n"
       << "   can only ever refute the hazard it was built to test. An smt sibling\n"
       << "   shares l1d and would not ping-pong, so the core choice excludes the\n"
       << "   measured core's thread_siblings and fails loud if none remains. */\n"
       << "class lshaz_aggressor {\n"
       << "public:\n"
       << "    explicit lshaz_aggressor(std::atomic<uint64_t>* target)\n"
       << "        : target_(target) {\n"
       << "        int core = pick_core();\n"
       << "        worker_ = std::thread([this, core] {\n"
       << "            cpu_set_t set; CPU_ZERO(&set); CPU_SET(core, &set);\n"
       << "            sched_setaffinity(0, sizeof(set), &set);\n"
       << "            uint64_t v = 0;\n"
       << "            while (!stop_.load(std::memory_order_acquire))\n"
       << "                target_->store(++v, std::memory_order_relaxed);\n"
       << "        });\n"
       << "    }\n"
       << "    ~lshaz_aggressor() {\n"
       << "        stop_.store(true, std::memory_order_release);\n"
       << "        if (worker_.joinable()) worker_.join();\n"
       << "    }\n"
       << "private:\n"
       << "    static std::set<int> siblings_of(int cpu) {\n"
       << "        std::set<int> out;\n"
       << "        char path[128];\n"
       << "        std::snprintf(path, sizeof(path),\n"
       << "            \"/sys/devices/system/cpu/cpu%d/topology/thread_siblings_list\", cpu);\n"
       << "        std::ifstream f(path);\n"
       << "        std::string tok;\n"
       << "        while (std::getline(f, tok, ',')) {\n"
       << "            auto dash = tok.find('-');\n"
       << "            if (dash == std::string::npos) out.insert(std::atoi(tok.c_str()));\n"
       << "            else {\n"
       << "                int lo = std::atoi(tok.substr(0, dash).c_str());\n"
       << "                int hi = std::atoi(tok.substr(dash + 1).c_str());\n"
       << "                for (int i = lo; i <= hi; ++i) out.insert(i);\n"
       << "            }\n"
       << "        }\n"
       << "        return out;\n"
       << "    }\n"
       << "    static int pick_core() {\n"
       << "        int measured = sched_getcpu();\n"
       << "        long n = sysconf(_SC_NPROCESSORS_ONLN);\n"
       << "        std::set<int> sib = siblings_of(measured);\n"
       << "        if (sib.empty()) {\n"
       << "            /* topology unreadable (container/restricted): still run, but\n"
       << "               state plainly that smt-distinctness is unverified. */\n"
       << "            for (int c = 0; c < n; ++c) if (c != measured) {\n"
       << "                std::fprintf(stderr, \"[lshaz] WARN: smt topology unreadable; \"\n"
       << "                    \"aggressor cpu=%d may be an smt sibling of measured cpu=%d \"\n"
       << "                    \"— coherence effect may be understated.\\n\", c, measured);\n"
       << "                return c;\n"
       << "            }\n"
       << "        } else {\n"
       << "            for (int c = 0; c < n; ++c)\n"
       << "                if (c != measured && sib.find(c) == sib.end()) {\n"
       << "                    std::fprintf(stderr, \"[lshaz] false-sharing aggressor: \"\n"
       << "                        \"measured_cpu=%d aggressor_cpu=%d (physical-distinct)\\n\",\n"
       << "                        measured, c);\n"
       << "                    return c;\n"
       << "                }\n"
       << "        }\n"
       << "        std::fprintf(stderr, \"[lshaz] FATAL: no physical core distinct from \"\n"
       << "            \"cpu %d — false sharing is unreproducible on one physical core.\\n\",\n"
       << "            measured);\n"
       << "        std::abort();\n"
       << "    }\n"
       << "    std::atomic<uint64_t>* target_;\n"
       << "    std::atomic<bool> stop_{false};\n"
       << "    std::thread worker_;\n"
       << "};\n";

    return {"src/common.h", os.str()};
}

ExperimentFile ExperimentSynthesizer::generateHarness(
    const LatencyHypothesis &hyp) {

    std::ostringstream os;
    os << "// Auto-generated harness for hypothesis " << hyp.hypothesisId << "\n"
       << "#include \"common.h\"\n\n"
       << "#include <chrono>\n"
       << "#include <cstdio>\n"
       << "#include <cstdlib>\n"
       << "#include <cstring>\n"
       << "#include <pthread.h>\n"
       << "#include <sched.h>\n"
       << "#include <thread>\n"
       << "#include <vector>\n\n"
       << "/* Kernels linked from separate TUs — prevents cross-variant optimization. */\n"
       << "extern void treatment_kernel(uint64_t iteration);\n"
       << "extern void control_kernel(uint64_t iteration);\n"
       << "extern void treatment_setup();\n"
       << "extern void control_setup();\n"
       << "extern void treatment_teardown();\n"
       << "extern void control_teardown();\n\n"
       << "static void pin_thread(int core) {\n"
       << "    cpu_set_t cpuset;\n"
       << "    CPU_ZERO(&cpuset);\n"
       << "    CPU_SET(core, &cpuset);\n"
       << "    pthread_setaffinity_np(pthread_self(), sizeof(cpuset), &cpuset);\n"
       << "}\n\n"
       << "static void run_variant(\n"
       << "    void (*setup)(),\n"
       << "    void (*kernel)(uint64_t),\n"
       << "    void (*teardown)(),\n"
       << "    std::vector<LatencySample> &samples,\n"
       << "    uint64_t warmup,\n"
       << "    uint64_t count) {\n\n"
       << "    setup();\n\n"
       << "    /* Warmup: prime i-cache, branch predictors, TLB. */\n"
       << "    for (uint64_t i = 0; i < warmup; ++i) {\n"
       << "        kernel(i);\n"
       << "        lshaz_do_not_optimize(i);\n"
       << "    }\n"
       << "    lshaz_clobber_memory();\n\n"
       << "    /* Measurement: lfence-bracketed rdtsc per iteration. */\n"
       << "    samples.resize(count);\n"
       << "    for (uint64_t i = 0; i < count; ++i) {\n"
       << "        samples[i].tsc_start = lshaz_rdtsc();\n"
       << "        kernel(i);\n"
       << "        samples[i].tsc_end = lshaz_rdtsc();\n"
       << "        lshaz_do_not_optimize(i);\n"
       << "    }\n\n"
       << "    teardown();\n"
       << "}\n\n"
       << "static void write_samples(const char *path,\n"
       << "                          const std::vector<LatencySample> &samples) {\n"
       << "    FILE *f = fopen(path, \"wb\");\n"
       << "    if (!f) { perror(path); return; }\n"
       << "    fwrite(samples.data(), sizeof(LatencySample), samples.size(), f);\n"
       << "    fclose(f);\n"
       << "}\n\n"
       << "int main(int argc, char **argv) {\n"
       << "    uint64_t warmup = 10000;\n"
       << "    uint64_t count  = 100000;\n"
       << "    int core        = 4;\n"
       << "    const char *variant = \"treatment\";\n\n"
       << "    for (int i = 1; i < argc; ++i) {\n"
       << "        if (strcmp(argv[i], \"--warmup\") == 0 && i+1 < argc)\n"
       << "            warmup = strtoull(argv[++i], nullptr, 10);\n"
       << "        else if (strcmp(argv[i], \"--count\") == 0 && i+1 < argc)\n"
       << "            count = strtoull(argv[++i], nullptr, 10);\n"
       << "        else if (strcmp(argv[i], \"--core\") == 0 && i+1 < argc)\n"
       << "            core = atoi(argv[++i]);\n"
       << "        else if (strcmp(argv[i], \"--variant\") == 0 && i+1 < argc)\n"
       << "            variant = argv[++i];\n"
       << "    }\n\n"
       << "    pin_thread(core);\n"
       << "    { auto r_ = std::system(\"mkdir -p results\"); (void)r_; }\n\n"
       << "    std::vector<LatencySample> samples;\n\n"
       << "    if (strcmp(variant, \"treatment\") == 0) {\n"
       << "        run_variant(treatment_setup, treatment_kernel,\n"
       << "                    treatment_teardown, samples, warmup, count);\n"
       << "        write_samples(\"results/treatment_samples.bin\", samples);\n"
       << "    } else {\n"
       << "        run_variant(control_setup, control_kernel,\n"
       << "                    control_teardown, samples, warmup, count);\n"
       << "        write_samples(\"results/control_samples.bin\", samples);\n"
       << "    }\n\n"
       << "    return 0;\n"
       << "}\n";

    return {"src/harness.cpp", os.str()};
}

ExperimentFile ExperimentSynthesizer::generateBuildScript(
    const LatencyHypothesis &hyp) {

    std::ostringstream os;
    os << "#!/bin/bash\n"
       << "set -euo pipefail\n\n"
       << "# " << hyp.hypothesisId << "\n"
       << "# Separate TUs prevent cross-variant optimization.\n\n"
       << "CXX=${CXX:-g++}\n"
       << "FLAGS=\"-O2 -march=native -fno-lto -std=c++20 -pthread\"\n\n"
       << "mkdir -p build results\n\n"
       << "$CXX $FLAGS -c src/treatment.cpp -o build/treatment.o\n"
       << "$CXX $FLAGS -c src/control.cpp -o build/control.o\n"
       << "$CXX $FLAGS src/harness.cpp build/treatment.o build/control.o "
       << "-o experiment -Isrc\n"
       << "$CXX $FLAGS src/analyze.cpp -o analyze\n\n"
       << "echo \"[lshaz] Build complete\"\n";

    return {"scripts/build.sh", os.str()};
}

ExperimentFile ExperimentSynthesizer::generateRunAll(
    const LatencyHypothesis &hyp,
    const MeasurementPlan &plan) {

    std::ostringstream os;
    os << "#!/bin/bash\n"
       << "set -euo pipefail\n\n"
       << "# Bail early if perf_event_paranoid blocks PMU access.\n"
       << "if [ -f /proc/sys/kernel/perf_event_paranoid ]; then\n"
       << "  PARANOID=$(cat /proc/sys/kernel/perf_event_paranoid)\n"
       << "  if [ \"$PARANOID\" -gt 1 ] && [ \"$(id -u)\" -ne 0 ]; then\n"
       << "    echo \"[lshaz] ERROR: perf_event_paranoid=$PARANOID (needs <=1 or root)\"\n"
       << "    echo \"  Fix: sudo sysctl kernel.perf_event_paranoid=1\"\n"
       << "    echo \"  Or run this script with sudo.\"\n"
       << "    exit 1\n"
       << "  fi\n"
       << "fi\n\n"
       << "echo \"[lshaz] Running full experiment: "
       << plan.hypothesisId << "\"\n\n"
       << "# Pin frequency, disable turbo/THP/ASLR/C-states.\n"
       << "sudo bash scripts/setup_env.sh\n\n"
       << "# Build\n"
       << "bash scripts/build.sh\n\n"
       << "mkdir -p results\n\n"
       << "# Run treatment\n"
       << "./experiment --variant treatment\n\n"
       << "# Run control\n"
       << "./experiment --variant control\n\n"
       << "# Verdict. Guarded so a non-confirmed result still restores the machine\n"
       << "# below; the honest status is propagated at exit. Exit codes mirror\n"
       << "# ExperimentVerdict: 0 confirmed, 1 refuted, 2 error, 3 inconclusive,\n"
       << "# 4 confounded.\n"
       << "VERDICT_STATUS=0\n"
       << "./analyze results/treatment_samples.bin results/control_samples.bin "
       << "--mde " << hyp.minimumDetectableEffect
       << " --alpha " << hyp.significanceLevel << " || VERDICT_STATUS=$?\n\n"
       << "# PMU collection passes.\n";

    for (const auto &script : plan.scripts) {
        if (script.name == "setup_env.sh" || script.name == "teardown_env.sh")
            continue;
        os << "bash scripts/" << script.name << "\n";
        os << "bash scripts/" << script.name << "\n\n";
    }

    os << "# Restore.\n"
       << "sudo bash scripts/teardown_env.sh\n\n"
       << "echo \"[lshaz] Experiment complete. Results in results/\"\n"
       << "# Non-zero == not CONFIRMED above the mde (refuted/inconclusive/confounded/\n"
       << "# error). Never masked — the caller sees system truth.\n"
       << "exit $VERDICT_STATUS\n";

    return {"scripts/run_all.sh", os.str()};
}

ExperimentFile ExperimentSynthesizer::generateMakefile() {
    std::ostringstream os;
    os << "CXX ?= g++\n"
       << "CXXFLAGS = -O2 -march=native -fno-lto -std=c++20 -pthread\n\n"
       << "all: experiment analyze\n\n"
       << "build/treatment.o: src/treatment.cpp src/common.h\n"
       << "\t@mkdir -p build\n"
       << "\t$(CXX) $(CXXFLAGS) -c $< -o $@ -Isrc\n\n"
       << "build/control.o: src/control.cpp src/common.h\n"
       << "\t@mkdir -p build\n"
       << "\t$(CXX) $(CXXFLAGS) -c $< -o $@ -Isrc\n\n"
       << "experiment: src/harness.cpp build/treatment.o build/control.o\n"
       << "\t$(CXX) $(CXXFLAGS) $^ -o $@ -Isrc\n\n"
       << "analyze: src/analyze.cpp\n"
       << "\t$(CXX) $(CXXFLAGS) $< -o $@\n\n"
       << "clean:\n"
       << "\trm -rf build experiment analyze results\n\n"
       << ".PHONY: all clean\n";

    return {"Makefile", os.str()};
}

ExperimentFile ExperimentSynthesizer::generateReadme(
    const LatencyHypothesis &hyp) {

    std::ostringstream os;
    os << "# Experiment: " << hyp.hypothesisId << "\n\n"
       << "## Hazard Class\n\n"
       << hazardClassName(hyp.hazardClass) << "\n\n"
       << "## Hypothesis\n\n"
       << "**H0:** " << hyp.H0 << "\n\n"
       << "**H1:** " << hyp.H1 << "\n\n"
       << "## Primary Metric\n\n"
       << hyp.primaryMetric.name << " (" << hyp.primaryMetric.unit << ")\n\n"
       << "## Statistical Parameters\n\n"
       << "- Minimum detectable effect: "
       << (hyp.minimumDetectableEffect * 100) << "%\n"
       << "- Significance level (α): " << hyp.significanceLevel << "\n"
       << "- Power (1-β): " << hyp.power << "\n"
       << "- Evidence tier: " << evidenceTierName(hyp.evidenceTier) << "\n\n"
       << "## Verdict\n\n"
       << "`analyze` bootstraps the (1−α) percentile CI of the relative p99.9 "
       << "effect — distribution-free, because latency is heavy-tailed and a "
       << "point compare of two tail quantiles cannot hold the false-positive "
       << "rate at α. A within-control split-half drift CI first gates runs "
       << "where machine drift is aliased with the arm label.\n\n"
       << "Exit codes (mirroring `ExperimentVerdict`): `0` confirmed (CI lower "
       << "bound > mde), `1` refuted (CI upper bound < mde), `2` error, `3` "
       << "inconclusive (CI straddles mde — under-powered at this sample count), "
       << "`4` confounded (control tail drifted ≥ mde within the run).\n\n"
       << "## Running\n\n"
       << "```bash\n"
       << "bash scripts/run_all.sh\n"
       << "```\n\n"
       << "Requires root for environment configuration.\n\n"
       << "## Limitations\n\n"
       << "Synthetic experiments cannot reproduce:\n"
       << "- Production traffic shape and microburst arrival patterns\n"
       << "- Full system interaction (NIC → kernel → userspace → response)\n"
       << "- Allocator fragmentation history\n"
       << "- OS scheduler interference beyond isolated cores\n"
       << "- Thermal throttling under sustained load\n\n"
       << "See BOUNDARIES.md for full epistemic limits.\n";

    return {"README.md", os.str()};
}

ExperimentFile ExperimentSynthesizer::generateHypothesisJson(
    const LatencyHypothesis &hyp) {

    std::ostringstream os;
    os << "{\n"
       << "  \"hypothesis_id\": \"" << hyp.hypothesisId << "\",\n"
       << "  \"finding_id\": \"" << hyp.findingId << "\",\n"
       << "  \"hazard_class\": \"" << hazardClassName(hyp.hazardClass) << "\",\n"
       << "  \"H0\": \"" << hyp.H0 << "\",\n"
       << "  \"H1\": \"" << hyp.H1 << "\",\n"
       << "  \"primary_metric\": {\n"
       << "    \"name\": \"" << hyp.primaryMetric.name << "\",\n"
       << "    \"unit\": \"" << hyp.primaryMetric.unit << "\",\n"
       << "    \"percentile\": \"" << hyp.primaryMetric.percentile << "\"\n"
       << "  },\n"
       << "  \"minimum_detectable_effect\": " << hyp.minimumDetectableEffect << ",\n"
       << "  \"significance_level\": " << hyp.significanceLevel << ",\n"
       << "  \"power\": " << hyp.power << ",\n"
       << "  \"evidence_tier\": \"" << evidenceTierName(hyp.evidenceTier) << "\",\n"
       << "  \"verdict\": \"" << verdictName(hyp.verdict) << "\"\n"
       << "}\n";

    return {"hypothesis.json", os.str()};
}

/* verdict step: distribution-free tail-regression test. */
ExperimentFile ExperimentSynthesizer::generateAnalyze(
    const LatencyHypothesis &hyp) {
    std::ostringstream os;
    os << "// Auto-generated verdict tool for " << hyp.hypothesisId << "\n"
       << "#include <cstdint>\n"
       << "#include <cstdio>\n"
       << "#include <cstdlib>\n"
       << "#include <cstring>\n"
       << "#include <cmath>\n"
       << "#include <algorithm>\n"
       << "#include <random>\n"
       << "#include <vector>\n\n"
       << "namespace {\n"
       << "struct Sample { uint64_t s, e; };\n\n"
       << "// time-ordered load; non-monotonic samples (migration / tsc wrap) are\n"
       << "// dropped loudly, never silently absorbed into the distribution.\n"
       << "bool load(const char *path, std::vector<uint64_t> &d) {\n"
       << "    FILE *f = fopen(path, \"rb\");\n"
       << "    if (!f) { fprintf(stderr, \"[lshaz] cannot open %s\\n\", path); return false; }\n"
       << "    Sample s; uint64_t dropped = 0;\n"
       << "    while (fread(&s, sizeof(s), 1, f) == 1) {\n"
       << "        if (s.e < s.s) { ++dropped; continue; }\n"
       << "        d.push_back(s.e - s.s);\n"
       << "    }\n"
       << "    fclose(f);\n"
       << "    if (dropped)\n"
       << "        fprintf(stderr, \"[lshaz] %s: dropped %llu non-monotonic sample(s)\\n\",\n"
       << "                path, (unsigned long long)dropped);\n"
       << "    return true;\n"
       << "}\n\n"
       << "// nearest-rank quantile via selection; reorders v in place.\n"
       << "uint64_t q_at(std::vector<uint64_t> &v, double q) {\n"
       << "    if (v.empty()) return 0;\n"
       << "    size_t i = (size_t)(q * (double)(v.size() - 1));\n"
       << "    std::nth_element(v.begin(), v.begin() + i, v.end());\n"
       << "    return v[i];\n"
       << "}\n\n"
       << "struct CI { double lo, hi, point; };\n\n"
       << "// percentile-method bootstrap of the relative effect (qA - qB)/qB at\n"
       << "// quantile q. distribution-free: correct for the heavy-tailed, skewed\n"
       << "// latency law where a t-test's normality assumption is invalid. scratch\n"
       << "// buffers are reused across reps — no per-rep heap churn.\n"
       << "CI boot_rel(const std::vector<uint64_t> &A, const std::vector<uint64_t> &B,\n"
       << "            double q, double alpha, int reps, std::mt19937_64 &rng) {\n"
       << "    if (A.empty() || B.empty()) return {0, 0, 0};\n"
       << "    std::vector<uint64_t> ra(A.size()), rb(B.size());\n"
       << "    std::vector<double> eff; eff.reserve(reps);\n"
       << "    for (int r = 0; r < reps; ++r) {\n"
       << "        for (size_t i = 0; i < A.size(); ++i) ra[i] = A[rng() % A.size()];\n"
       << "        for (size_t i = 0; i < B.size(); ++i) rb[i] = B[rng() % B.size()];\n"
       << "        double qa = (double)q_at(ra, q), qb = (double)q_at(rb, q);\n"
       << "        eff.push_back(qb ? (qa - qb) / qb : 0.0);\n"
       << "    }\n"
       << "    std::sort(eff.begin(), eff.end());\n"
       << "    auto pick = [&](double p) {\n"
       << "        return eff[(size_t)(p * (double)(eff.size() - 1))];\n"
       << "    };\n"
       << "    std::vector<uint64_t> pa(A), pb(B);\n"
       << "    double a0 = (double)q_at(pa, q), b0 = (double)q_at(pb, q);\n"
       << "    return {pick(alpha / 2.0), pick(1.0 - alpha / 2.0),\n"
       << "            b0 ? (a0 - b0) / b0 : 0.0};\n"
       << "}\n"
       << "} // namespace\n\n"
       << "int main(int argc, char **argv) {\n"
       << "    double mde   = " << hyp.minimumDetectableEffect << ";\n"
       << "    double alpha = " << hyp.significanceLevel << ";  /* ci at 1-alpha */\n"
       << "    double power = " << hyp.power << ";     /* target 1-beta (reporting) */\n"
       << "    int    reps  = 2000;\n"
       << "    uint64_t seed = 0x9E3779B97F4A7C15ULL;  /* fixed -> reproducible verdict */\n"
       << "    const char *tp = argc > 1 ? argv[1] : \"results/treatment_samples.bin\";\n"
       << "    const char *cp = argc > 2 ? argv[2] : \"results/control_samples.bin\";\n"
       << "    for (int i = 3; i < argc; ++i) {\n"
       << "        if (!strcmp(argv[i], \"--mde\")       && i+1 < argc) mde   = atof(argv[++i]);\n"
       << "        else if (!strcmp(argv[i], \"--alpha\") && i+1 < argc) alpha = atof(argv[++i]);\n"
       << "        else if (!strcmp(argv[i], \"--bootstrap\") && i+1 < argc) reps = atoi(argv[++i]);\n"
       << "        else if (!strcmp(argv[i], \"--seed\")  && i+1 < argc) seed = strtoull(argv[++i], 0, 0);\n"
       << "    }\n\n"
       << "    std::vector<uint64_t> t, c;  /* time-ordered */\n"
       << "    if (!load(tp, t) || !load(cp, c)) return 2;\n"
       << "    if (t.empty() || c.empty()) {\n"
       << "        fprintf(stderr, \"[lshaz] FATAL: empty sample set — cannot judge.\\n\");\n"
       << "        return 2;\n"
       << "    }\n\n"
       << "    std::mt19937_64 rng(seed);\n"
       << "    const double Q = 0.999;\n\n"
       << "    /* confound guard: split control by wall-clock order. if the tail moved\n"
       << "       within the control run by as much as the effect we seek, the between-\n"
       << "       arm delta is aliased with drift and no verdict is trustworthy. */\n"
       << "    size_t h = c.size() / 2;\n"
       << "    std::vector<uint64_t> c1(c.begin(), c.begin() + h);\n"
       << "    std::vector<uint64_t> c2(c.begin() + h, c.end());\n"
       << "    CI drift = boot_rel(c2, c1, Q, alpha, reps, rng);\n"
       << "    bool drift_sig = (drift.lo > 0.0 || drift.hi < 0.0) && fabs(drift.point) >= mde;\n\n"
       << "    /* between-arm effect. */\n"
       << "    CI e = boot_rel(t, c, Q, alpha, reps, rng);\n\n"
       << "    /* point p50/p99.9 for the table (copies; boot already consumed order). */\n"
       << "    std::vector<uint64_t> ts(t), cs(c);\n"
       << "    std::sort(ts.begin(), ts.end()); std::sort(cs.begin(), cs.end());\n"
       << "    auto pctl = [](const std::vector<uint64_t> &v, double p) {\n"
       << "        return v[(size_t)(p * (double)(v.size() - 1))];\n"
       << "    };\n\n"
       << "    printf(\"samples: control=%zu treatment=%zu  (bootstrap reps=%d, alpha=%.3f)\\n\",\n"
       << "           c.size(), t.size(), reps, alpha);\n"
       << "    printf(\"cycles          control    treatment\\n\");\n"
       << "    printf(\"  p50        %10llu %10llu\\n\",\n"
       << "           (unsigned long long)pctl(cs,0.50), (unsigned long long)pctl(ts,0.50));\n"
       << "    printf(\"  p99.9      %10llu %10llu\\n\",\n"
       << "           (unsigned long long)pctl(cs,Q), (unsigned long long)pctl(ts,Q));\n"
       << "    printf(\"effect(p99.9): %+.1f%%  ci[%.3f]=[%+.1f%%, %+.1f%%]  mde=%.1f%%\\n\",\n"
       << "           e.point*100, 1-alpha, e.lo*100, e.hi*100, mde*100);\n"
       << "    printf(\"control drift: %+.1f%%  ci=[%+.1f%%, %+.1f%%]\\n\",\n"
       << "           drift.point*100, drift.lo*100, drift.hi*100);\n\n"
       << "    if (drift_sig) {\n"
       << "        printf(\"VERDICT: CONFOUNDED (control tail drifted >= mde within the run; \"\n"
       << "               \"pin freq/turbo/c-states or interleave arms)\\n\");\n"
       << "        return 4;\n"
       << "    }\n"
       << "    if (e.lo > mde) { printf(\"VERDICT: CONFIRMED\\n\"); return 0; }\n"
       << "    if (e.hi < mde) { printf(\"VERDICT: REFUTED\\n\"); return 1; }\n"
       << "    /* ci straddles mde: cannot resolve. flag under-power honestly. */\n"
       << "    if ((e.hi - e.lo) / 2.0 > mde)\n"
       << "        printf(\"  under-powered: ci half-width %.1f%% > mde %.1f%% \"\n"
       << "               \"(raise --count toward target power %.2f)\\n\",\n"
       << "               (e.hi-e.lo)/2.0*100, mde*100, power);\n"
       << "    printf(\"VERDICT: INCONCLUSIVE\\n\");\n"
       << "    return 3;\n"
       << "}\n";
    return {"src/analyze.cpp", os.str()};
}

/*
 * Per-hazard-class kernel synthesis.
 *
 * Each pair (treatment, control) isolates exactly one structural variable.
 * Treatment reproduces the hazard; control removes it. Both are compiled
 * as separate TUs and linked into a single binary to prevent the compiler
 * from optimizing across the comparison boundary.
 *
 * Invariant: every kernel defines exactly {setup, teardown, kernel}.
 * The harness calls them via function pointer — no devirtualization.
 */

namespace {

unsigned evidenceUnsigned(const LatencyHypothesis &hyp, const char *key,
                          unsigned fallback) {
    auto it = hyp.structuralEvidence.find(key);
    if (it == hyp.structuralEvidence.end()) return fallback;
    std::string val = it->second;
    if (!val.empty() && val.back() == 'B') val.pop_back();
    try { return static_cast<unsigned>(std::stoul(val)); }
    catch (...) { return fallback; }
}

std::string evidenceStr(const LatencyHypothesis &hyp, const char *key,
                        const char *fallback = "") {
    auto it = hyp.structuralEvidence.find(key);
    if (it == hyp.structuralEvidence.end()) return fallback;
    return it->second;
}

unsigned padToLine(unsigned sz) { return ((sz + 63u) / 64u) * 64u; }

} // anonymous namespace

/* FL001 — CacheGeometry: multi-line struct vs single-line aligned. */
static ExperimentFile genTreatmentCacheGeometry(const LatencyHypothesis &hyp) {
    unsigned sz = evidenceUnsigned(hyp, "sizeof", 128);
    unsigned nlines = evidenceUnsigned(hyp, "lines_spanned", 2);
    if (sz <= 64) sz = 65; /* must span >1 line */

    std::ostringstream os;
    os << "// Treatment kernel: CacheGeometry (FL001)\n"
       << "// Original struct size: " << sz << "B spanning " << nlines
       << " cache line(s)\n"
       << "#include \"common.h\"\n\n"
       << "struct Treatment {\n"
       << "    char payload[" << sz << "];\n"
       << "};\n\n"
       << "static constexpr unsigned N = 4096;\n"
       << "static Treatment *items;\n\n"
       << "void treatment_setup() {\n"
       << "    items = new Treatment[N];\n"
       << "    memset(items, 0x42, sizeof(Treatment) * N);\n"
       << "}\n\n"
       << "void treatment_teardown() { delete[] items; }\n\n"
       << "void treatment_kernel(uint64_t iteration) {\n"
       << "    auto &t = items[iteration % N];\n"
       << "    /* Touch first+last byte: forces load across line boundary. */\n"
       << "    t.payload[0]++;\n"
       << "    t.payload[" << (sz - 1) << "]++;\n"
       << "    lshaz_do_not_optimize(t);\n"
       << "}\n";
    return {"src/treatment.cpp", os.str()};
}

static ExperimentFile genControlCacheGeometry(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Control kernel: CacheGeometry (FL001)\n"
       << "// Struct fits within a single 64B cache line.\n"
       << "#include \"common.h\"\n\n"
       << "struct alignas(64) Control {\n"
       << "    char payload[56];\n"
       << "};\n\n"
       << "static constexpr unsigned N = 4096;\n"
       << "static Control *items;\n\n"
       << "void control_setup() {\n"
       << "    items = new Control[N];\n"
       << "    memset(items, 0x42, sizeof(Control) * N);\n"
       << "}\n\n"
       << "void control_teardown() { delete[] items; }\n\n"
       << "void control_kernel(uint64_t iteration) {\n"
       << "    auto &c = items[iteration % N];\n"
       << "    c.payload[0]++;\n"
       << "    c.payload[55]++;\n"
       << "    lshaz_do_not_optimize(c);\n"
       << "}\n";
    return {"src/control.cpp", os.str()};
}

/* FL002 */
static ExperimentFile genTreatmentFalseSharing(const LatencyHypothesis &hyp) {
    /* Reproduce the *actual* finding: two hot fields co-resident on one line,
       padded to the real record footprint so allocation/layout tracks the
       source struct. 2x atomic<uint64_t> = 16B; pad out the rest. */
    unsigned sz = evidenceUnsigned(hyp, "sizeof", 64);
    std::string ty = evidenceStr(hyp, "type_name", "(unknown)");
    unsigned pad = sz > 16 ? sz - 16 : 0;

    std::ostringstream os;
    os << "// Treatment kernel: FalseSharing (FL002)\n"
       << "// Source struct: " << ty << " (" << sz << "B)\n"
       << "// a@0 and b@8 share one 64B line; a sibling core writes b.\n"
       << "#include \"common.h\"\n\n"
       << "struct Contended {\n"
       << "    std::atomic<uint64_t> a{0};\n"
       << "    std::atomic<uint64_t> b{0};\n";
    if (pad)
        os << "    char pad[" << pad << "];\n";
    os << "};\n\n"
       << "static Contended *shared;\n"
       << "static lshaz_aggressor *agg;\n\n"
       << "void treatment_setup() {\n"
       << "    shared = new Contended;\n"
       << "    agg = new lshaz_aggressor(&shared->b);  /* contends a's line */\n"
       << "}\n\n"
       << "/* stop the writer before freeing its target. */\n"
       << "void treatment_teardown() { delete agg; delete shared; }\n\n"
       << "/* RMW, not store: a relaxed store retires into the store buffer and\n"
       << "   lfence does not drain it, so the rdtsc bracket never sees the RFO\n"
       << "   stall and treatment reads identical to control. A locked fetch_add\n"
       << "   cannot retire until it owns the line — that exposes the invalidation\n"
       << "   latency this finding is about. Measured +50% p99.9 on Zen4. */\n"
       << "void treatment_kernel(uint64_t /*iteration*/) {\n"
       << "    shared->a.fetch_add(1, std::memory_order_relaxed);\n"
       << "    lshaz_do_not_optimize(shared->a);\n"
       << "}\n";
    return {"src/treatment.cpp", os.str()};
}

static ExperimentFile genControlFalseSharing(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Control kernel: FalseSharing (FL002)\n"
       << "// a and b on separate 64B lines; sibling core writes b (no ping-pong).\n"
       << "#include \"common.h\"\n\n"
       << "struct alignas(64) LineA { std::atomic<uint64_t> a{0}; char pad[56]; };\n"
       << "struct alignas(64) LineB { std::atomic<uint64_t> b{0}; char pad[56]; };\n\n"
       << "static LineA *la;\n"
       << "static LineB *lb;\n"
       << "static lshaz_aggressor *agg;\n\n"
       << "void control_setup() {\n"
       << "    la = new LineA;\n"
       << "    lb = new LineB;\n"
       << "    agg = new lshaz_aggressor(&lb->b);  /* distinct line — no contention */\n"
       << "}\n\n"
       << "void control_teardown() { delete agg; delete la; delete lb; }\n\n"
       << "/* same RMW as treatment — the only changed variable is line residence. */\n"
       << "void control_kernel(uint64_t /*iteration*/) {\n"
       << "    la->a.fetch_add(1, std::memory_order_relaxed);\n"
       << "    lshaz_do_not_optimize(la->a);\n"
       << "}\n";
    return {"src/control.cpp", os.str()};
}

/* FL010 — AtomicOrdering: seq_cst vs release/acquire. */
static ExperimentFile genTreatmentAtomicOrdering(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Treatment kernel: AtomicOrdering (FL010)\n"
       << "// seq_cst store in hot loop.\n"
       << "#include \"common.h\"\n\n"
       << "static std::atomic<uint64_t> counter{0};\n\n"
       << "void treatment_setup() { counter.store(0); }\n"
       << "void treatment_teardown() {}\n\n"
       << "void treatment_kernel(uint64_t iteration) {\n"
       << "    counter.store(iteration, std::memory_order_seq_cst);\n"
       << "    uint64_t v = counter.load(std::memory_order_seq_cst);\n"
       << "    lshaz_do_not_optimize(v);\n"
       << "}\n";
    return {"src/treatment.cpp", os.str()};
}

static ExperimentFile genControlAtomicOrdering(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Control kernel: AtomicOrdering (FL010)\n"
       << "// release/acquire in hot loop.\n"
       << "#include \"common.h\"\n\n"
       << "static std::atomic<uint64_t> counter{0};\n\n"
       << "void control_setup() { counter.store(0); }\n"
       << "void control_teardown() {}\n\n"
       << "void control_kernel(uint64_t iteration) {\n"
       << "    counter.store(iteration, std::memory_order_release);\n"
       << "    uint64_t v = counter.load(std::memory_order_acquire);\n"
       << "    lshaz_do_not_optimize(v);\n"
       << "}\n";
    return {"src/control.cpp", os.str()};
}

/* FL011 — AtomicContention: shared atomic vs thread-local sharding. */
static ExperimentFile genTreatmentAtomicContention(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Treatment kernel: AtomicContention (FL011)\n"
       << "#include \"common.h\"\n\n"
       << "static std::atomic<uint64_t> shared_counter{0};\n\n"
       << "void treatment_setup() { shared_counter.store(0); }\n"
       << "void treatment_teardown() {}\n\n"
       << "void treatment_kernel(uint64_t iteration) {\n"
       << "    shared_counter.fetch_add(1, std::memory_order_relaxed);\n"
       << "    lshaz_do_not_optimize(shared_counter);\n"
       << "}\n";
    return {"src/treatment.cpp", os.str()};
}

static ExperimentFile genControlAtomicContention(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Control kernel: AtomicContention (FL011)\n"
       << "// Thread-local counter, no contention.\n"
       << "#include \"common.h\"\n\n"
       << "static thread_local uint64_t local_counter = 0;\n\n"
       << "void control_setup() { local_counter = 0; }\n"
       << "void control_teardown() {}\n\n"
       << "void control_kernel(uint64_t iteration) {\n"
       << "    ++local_counter;\n"
       << "    lshaz_do_not_optimize(local_counter);\n"
       << "}\n";
    return {"src/control.cpp", os.str()};
}

/* FL012 — LockContention: mutex vs lock-free atomic. */
static ExperimentFile genTreatmentLockContention(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Treatment kernel: LockContention (FL012)\n"
       << "#include \"common.h\"\n"
       << "#include <mutex>\n\n"
       << "static std::mutex mtx;\n"
       << "static uint64_t shared_val = 0;\n\n"
       << "void treatment_setup() { shared_val = 0; }\n"
       << "void treatment_teardown() {}\n\n"
       << "void treatment_kernel(uint64_t iteration) {\n"
       << "    std::lock_guard<std::mutex> lock(mtx);\n"
       << "    shared_val += iteration;\n"
       << "    lshaz_do_not_optimize(shared_val);\n"
       << "}\n";
    return {"src/treatment.cpp", os.str()};
}

static ExperimentFile genControlLockContention(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Control kernel: LockContention (FL012)\n"
       << "// Lock-free atomic increment.\n"
       << "#include \"common.h\"\n\n"
       << "static std::atomic<uint64_t> shared_val{0};\n\n"
       << "void control_setup() { shared_val.store(0); }\n"
       << "void control_teardown() {}\n\n"
       << "void control_kernel(uint64_t iteration) {\n"
       << "    shared_val.fetch_add(iteration, std::memory_order_relaxed);\n"
       << "    lshaz_do_not_optimize(shared_val);\n"
       << "}\n";
    return {"src/control.cpp", os.str()};
}

/* FL020 — HeapAllocation: per-iteration malloc vs preallocated. */
static ExperimentFile genTreatmentHeapAllocation(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Treatment kernel: HeapAllocation (FL020)\n"
       << "// malloc/free per iteration.\n"
       << "#include \"common.h\"\n"
       << "#include <cstdlib>\n\n"
       << "void treatment_setup() {}\n"
       << "void treatment_teardown() {}\n\n"
       << "void treatment_kernel(uint64_t iteration) {\n"
       << "    void *p = malloc(256);\n"
       << "    memset(p, static_cast<int>(iteration & 0xFF), 256);\n"
       << "    lshaz_do_not_optimize(p);\n"
       << "    free(p);\n"
       << "}\n";
    return {"src/treatment.cpp", os.str()};
}

static ExperimentFile genControlHeapAllocation(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Control kernel: HeapAllocation (FL020)\n"
       << "// Pre-allocated buffer, no malloc in hot loop.\n"
       << "#include \"common.h\"\n\n"
       << "static char *buf;\n\n"
       << "void control_setup() {\n"
       << "    buf = static_cast<char *>(malloc(256));\n"
       << "}\n\n"
       << "void control_teardown() { free(buf); }\n\n"
       << "void control_kernel(uint64_t iteration) {\n"
       << "    memset(buf, static_cast<int>(iteration & 0xFF), 256);\n"
       << "    lshaz_do_not_optimize(buf);\n"
       << "}\n";
    return {"src/control.cpp", os.str()};
}

/* FL021 — StackPressure: large frame (>1 page) vs sub-page. */
static ExperimentFile genTreatmentStackPressure(const LatencyHypothesis &hyp) {
    unsigned frame = evidenceUnsigned(hyp, "estimated_frame", 8192);
    if (frame < 4096) frame = 4096; /* floor at one page */
    std::ostringstream os;
    os << "// Treatment kernel: StackPressure (FL021)\n"
       << "// Large stack frame: " << frame << " bytes.\n"
       << "#include \"common.h\"\n\n"
       << "void treatment_setup() {}\n"
       << "void treatment_teardown() {}\n\n"
       << "__attribute__((noinline))\n"
       << "void treatment_kernel(uint64_t iteration) {\n"
       << "    char buf[" << frame << "];\n"
       << "    memset(buf, static_cast<int>(iteration & 0xFF), sizeof(buf));\n"
       << "    lshaz_do_not_optimize(buf[0]);\n"
       << "    lshaz_do_not_optimize(buf[" << (frame - 1) << "]);\n"
       << "}\n";
    return {"src/treatment.cpp", os.str()};
}

static ExperimentFile genControlStackPressure(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Control kernel: StackPressure (FL021)\n"
       << "// Small stack frame (< one page).\n"
       << "#include \"common.h\"\n\n"
       << "void control_setup() {}\n"
       << "void control_teardown() {}\n\n"
       << "__attribute__((noinline))\n"
       << "void control_kernel(uint64_t iteration) {\n"
       << "    char buf[64];\n"
       << "    memset(buf, static_cast<int>(iteration & 0xFF), sizeof(buf));\n"
       << "    lshaz_do_not_optimize(buf[0]);\n"
       << "    lshaz_do_not_optimize(buf[63]);\n"
       << "}\n";
    return {"src/control.cpp", os.str()};
}

/* FL030 — VirtualDispatch: polymorphic (4 targets) vs monomorphic. */
static ExperimentFile genTreatmentVirtualDispatch(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Treatment kernel: VirtualDispatch (FL030)\n"
       << "#include \"common.h\"\n\n"
       << "struct Base {\n"
       << "    virtual uint64_t process(uint64_t v) = 0;\n"
       << "    virtual ~Base() = default;\n"
       << "};\n"
       << "struct ImplA : Base { uint64_t process(uint64_t v) override { return v + 1; } };\n"
       << "struct ImplB : Base { uint64_t process(uint64_t v) override { return v + 2; } };\n"
       << "struct ImplC : Base { uint64_t process(uint64_t v) override { return v + 3; } };\n"
       << "struct ImplD : Base { uint64_t process(uint64_t v) override { return v + 4; } };\n\n"
       << "static constexpr unsigned NTYPES = 4;\n"
       << "static Base *targets[NTYPES];\n\n"
       << "void treatment_setup() {\n"
       << "    targets[0] = new ImplA;\n"
       << "    targets[1] = new ImplB;\n"
       << "    targets[2] = new ImplC;\n"
       << "    targets[3] = new ImplD;\n"
       << "}\n\n"
       << "void treatment_teardown() {\n"
       << "    for (auto *t : targets) delete t;\n"
       << "}\n\n"
       << "void treatment_kernel(uint64_t iteration) {\n"
       << "    uint64_t v = targets[iteration % NTYPES]->process(iteration);\n"
       << "    lshaz_do_not_optimize(v);\n"
       << "}\n";
    return {"src/treatment.cpp", os.str()};
}

static ExperimentFile genControlVirtualDispatch(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Control kernel: VirtualDispatch (FL030)\n"
       << "// Direct (non-virtual) call — monomorphic.\n"
       << "#include \"common.h\"\n\n"
       << "struct Direct {\n"
       << "    uint64_t process(uint64_t v) { return v + 1; }\n"
       << "};\n\n"
       << "static Direct *target;\n\n"
       << "void control_setup() { target = new Direct; }\n"
       << "void control_teardown() { delete target; }\n\n"
       << "void control_kernel(uint64_t iteration) {\n"
       << "    uint64_t v = target->process(iteration);\n"
       << "    lshaz_do_not_optimize(v);\n"
       << "}\n";
    return {"src/control.cpp", os.str()};
}

/* FL031 — StdFunction: type-erased callable vs template-inlined. */
static ExperimentFile genTreatmentStdFunction(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Treatment kernel: StdFunction (FL031)\n"
       << "#include \"common.h\"\n"
       << "#include <functional>\n\n"
       << "static std::function<uint64_t(uint64_t)> fn;\n\n"
       << "void treatment_setup() {\n"
       << "    fn = [](uint64_t v) -> uint64_t { return v + 1; };\n"
       << "}\n\n"
       << "void treatment_teardown() { fn = nullptr; }\n\n"
       << "void treatment_kernel(uint64_t iteration) {\n"
       << "    uint64_t v = fn(iteration);\n"
       << "    lshaz_do_not_optimize(v);\n"
       << "}\n";
    return {"src/treatment.cpp", os.str()};
}

static ExperimentFile genControlStdFunction(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Control kernel: StdFunction (FL031)\n"
       << "// Template callable — no indirection.\n"
       << "#include \"common.h\"\n\n"
       << "static auto fn = [](uint64_t v) -> uint64_t { return v + 1; };\n\n"
       << "void control_setup() {}\n"
       << "void control_teardown() {}\n\n"
       << "void control_kernel(uint64_t iteration) {\n"
       << "    uint64_t v = fn(iteration);\n"
       << "    lshaz_do_not_optimize(v);\n"
       << "}\n";
    return {"src/control.cpp", os.str()};
}

/* FL040 — GlobalState: mutable global vs local accumulator. */
static ExperimentFile genTreatmentGlobalState(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Treatment kernel: GlobalState (FL040)\n"
       << "// Mutable global accessed in hot loop.\n"
       << "#include \"common.h\"\n\n"
       << "static uint64_t global_state = 0;\n\n"
       << "void treatment_setup() { global_state = 0; }\n"
       << "void treatment_teardown() {}\n\n"
       << "void treatment_kernel(uint64_t iteration) {\n"
       << "    global_state += iteration;\n"
       << "    lshaz_do_not_optimize(global_state);\n"
       << "}\n";
    return {"src/treatment.cpp", os.str()};
}

static ExperimentFile genControlGlobalState(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Control kernel: GlobalState (FL040)\n"
       << "// Local accumulator, no global state.\n"
       << "#include \"common.h\"\n\n"
       << "void control_setup() {}\n"
       << "void control_teardown() {}\n\n"
       << "void control_kernel(uint64_t iteration) {\n"
       << "    uint64_t local = iteration;\n"
       << "    local += iteration;\n"
       << "    lshaz_do_not_optimize(local);\n"
       << "}\n";
    return {"src/control.cpp", os.str()};
}

/* FL041 — ContendedQueue: packed head/tail vs cache-line-padded. */
static ExperimentFile genTreatmentContendedQueue(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Treatment kernel: ContendedQueue (FL041)\n"
       << "// head/tail atomics on same cache line.\n"
       << "#include \"common.h\"\n\n"
       << "struct Queue {\n"
       << "    std::atomic<uint64_t> head{0};\n"
       << "    std::atomic<uint64_t> tail{0};\n"
       << "};\n\n"
       << "static Queue *q;\n\n"
       << "void treatment_setup() { q = new Queue; }\n"
       << "void treatment_teardown() { delete q; }\n\n"
       << "void treatment_kernel(uint64_t iteration) {\n"
       << "    q->tail.store(iteration, std::memory_order_release);\n"
       << "    uint64_t h = q->head.load(std::memory_order_acquire);\n"
       << "    lshaz_do_not_optimize(h);\n"
       << "}\n";
    return {"src/treatment.cpp", os.str()};
}

static ExperimentFile genControlContendedQueue(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Control kernel: ContendedQueue (FL041)\n"
       << "// head/tail on separate cache lines.\n"
       << "#include \"common.h\"\n\n"
       << "struct alignas(64) PaddedQueue {\n"
       << "    alignas(64) std::atomic<uint64_t> head{0};\n"
       << "    alignas(64) std::atomic<uint64_t> tail{0};\n"
       << "};\n\n"
       << "static PaddedQueue *q;\n\n"
       << "void control_setup() { q = new PaddedQueue; }\n"
       << "void control_teardown() { delete q; }\n\n"
       << "void control_kernel(uint64_t iteration) {\n"
       << "    q->tail.store(iteration, std::memory_order_release);\n"
       << "    uint64_t h = q->head.load(std::memory_order_acquire);\n"
       << "    lshaz_do_not_optimize(h);\n"
       << "}\n";
    return {"src/control.cpp", os.str()};
}

/* FL050 — DeepConditional: deep branch chain vs branchless. */
static ExperimentFile genTreatmentDeepConditional(const LatencyHypothesis &hyp) {
    unsigned depth = evidenceUnsigned(hyp, "depth", 8);
    if (depth < 4) depth = 4; /* minimum for measurable misprediction */
    std::ostringstream os;
    os << "// Treatment kernel: DeepConditional (FL050)\n"
       << "// " << depth << "-deep branch chain.\n"
       << "#include \"common.h\"\n\n"
       << "void treatment_setup() {}\n"
       << "void treatment_teardown() {}\n\n"
       << "__attribute__((noinline))\n"
       << "void treatment_kernel(uint64_t iteration) {\n"
       << "    uint64_t v = iteration;\n";
    for (unsigned i = 0; i < depth; ++i)
        os << "    if (v & " << (1ULL << (i % 16)) << ") v += " << (i + 1) << ";\n";
    os << "    lshaz_do_not_optimize(v);\n"
       << "}\n";
    return {"src/treatment.cpp", os.str()};
}

static ExperimentFile genControlDeepConditional(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Control kernel: DeepConditional (FL050)\n"
       << "// Branchless arithmetic.\n"
       << "#include \"common.h\"\n\n"
       << "void control_setup() {}\n"
       << "void control_teardown() {}\n\n"
       << "__attribute__((noinline))\n"
       << "void control_kernel(uint64_t iteration) {\n"
       << "    uint64_t v = iteration * 3 + 7;\n"
       << "    lshaz_do_not_optimize(v);\n"
       << "}\n";
    return {"src/control.cpp", os.str()};
}

/* FL060 — NUMALocality: heap-allocated (first-touch) vs stack-local. */
static ExperimentFile genTreatmentNUMALocality(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Treatment kernel: NUMALocality (FL060)\n"
       << "// Allocate on node 0, access from (potentially) another node.\n"
       << "#include \"common.h\"\n\n"
       << "static constexpr unsigned N = 1 << 20; // 1M entries\n"
       << "static uint64_t *data;\n\n"
       << "void treatment_setup() {\n"
       << "    data = new uint64_t[N];\n"
       << "    memset(data, 0x42, N * sizeof(uint64_t));\n"
       << "}\n\n"
       << "void treatment_teardown() { delete[] data; }\n\n"
       << "void treatment_kernel(uint64_t iteration) {\n"
       << "    data[iteration % N] += iteration;\n"
       << "    lshaz_do_not_optimize(data[iteration % N]);\n"
       << "}\n";
    return {"src/treatment.cpp", os.str()};
}

static ExperimentFile genControlNUMALocality(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Control kernel: NUMALocality (FL060)\n"
       << "// Local stack buffer — guaranteed same-node.\n"
       << "#include \"common.h\"\n\n"
       << "void control_setup() {}\n"
       << "void control_teardown() {}\n\n"
       << "void control_kernel(uint64_t iteration) {\n"
       << "    uint64_t local[64];\n"
       << "    local[iteration % 64] += iteration;\n"
       << "    lshaz_do_not_optimize(local[iteration % 64]);\n"
       << "}\n";
    return {"src/control.cpp", os.str()};
}

/* Fallback: stub kernels for hazard classes without synthetic reproduction. */
static ExperimentFile genTreatmentFallback(const LatencyHypothesis &hyp) {
    std::ostringstream os;
    os << "// Treatment kernel: " << hazardClassName(hyp.hazardClass) << "\n"
       << "// Placeholder — edit to reproduce the specific hazard.\n"
       << "#include \"common.h\"\n\n"
       << "void treatment_setup() {}\n"
       << "void treatment_teardown() {}\n\n"
       << "void treatment_kernel(uint64_t iteration) {\n"
       << "    lshaz_do_not_optimize(iteration);\n"
       << "}\n";
    return {"src/treatment.cpp", os.str()};
}

static ExperimentFile genControlFallback(const LatencyHypothesis &hyp) {
    std::ostringstream os;
    os << "// Control kernel: " << hazardClassName(hyp.hazardClass) << "\n"
       << "// Placeholder — edit to implement the mitigated variant.\n"
       << "#include \"common.h\"\n\n"
       << "void control_setup() {}\n"
       << "void control_teardown() {}\n\n"
       << "void control_kernel(uint64_t iteration) {\n"
       << "    lshaz_do_not_optimize(iteration);\n"
       << "}\n";
    return {"src/control.cpp", os.str()};
}

ExperimentFile ExperimentSynthesizer::generateTreatment(
    const LatencyHypothesis &hyp) {
    switch (hyp.hazardClass) {
        case HazardClass::CacheGeometry:       return genTreatmentCacheGeometry(hyp);
        case HazardClass::FalseSharing:        return genTreatmentFalseSharing(hyp);
        case HazardClass::AtomicOrdering:      return genTreatmentAtomicOrdering(hyp);
        case HazardClass::AtomicContention:    return genTreatmentAtomicContention(hyp);
        case HazardClass::LockContention:      return genTreatmentLockContention(hyp);
        case HazardClass::HeapAllocation:      return genTreatmentHeapAllocation(hyp);
        case HazardClass::StackPressure:       return genTreatmentStackPressure(hyp);
        case HazardClass::VirtualDispatch:     return genTreatmentVirtualDispatch(hyp);
        case HazardClass::StdFunction:         return genTreatmentStdFunction(hyp);
        case HazardClass::GlobalState:         return genTreatmentGlobalState(hyp);
        case HazardClass::ContendedQueue:      return genTreatmentContendedQueue(hyp);
        case HazardClass::DeepConditional:     return genTreatmentDeepConditional(hyp);
        case HazardClass::NUMALocality:        return genTreatmentNUMALocality(hyp);
        default:                               return genTreatmentFallback(hyp);
    }
}

ExperimentFile ExperimentSynthesizer::generateControl(
    const LatencyHypothesis &hyp) {
    switch (hyp.hazardClass) {
        case HazardClass::CacheGeometry:       return genControlCacheGeometry(hyp);
        case HazardClass::FalseSharing:        return genControlFalseSharing(hyp);
        case HazardClass::AtomicOrdering:      return genControlAtomicOrdering(hyp);
        case HazardClass::AtomicContention:    return genControlAtomicContention(hyp);
        case HazardClass::LockContention:      return genControlLockContention(hyp);
        case HazardClass::HeapAllocation:      return genControlHeapAllocation(hyp);
        case HazardClass::StackPressure:       return genControlStackPressure(hyp);
        case HazardClass::VirtualDispatch:     return genControlVirtualDispatch(hyp);
        case HazardClass::StdFunction:         return genControlStdFunction(hyp);
        case HazardClass::GlobalState:         return genControlGlobalState(hyp);
        case HazardClass::ContendedQueue:      return genControlContendedQueue(hyp);
        case HazardClass::DeepConditional:     return genControlDeepConditional(hyp);
        case HazardClass::NUMALocality:        return genControlNUMALocality(hyp);
        default:                               return genControlFallback(hyp);
    }
}

ExperimentBundle ExperimentSynthesizer::synthesize(
    const LatencyHypothesis &hypothesis,
    const MeasurementPlan &plan,
    const std::string &outputDir) {

    ExperimentBundle bundle;
    bundle.findingId = hypothesis.findingId;
    bundle.hypothesisId = hypothesis.hypothesisId;
    bundle.outputDir = outputDir;
    bundle.measurementPlan = plan;

    bundle.files.push_back(generateCommonHeader(hypothesis));
    bundle.files.push_back(generateHarness(hypothesis));
    bundle.files.push_back(generateTreatment(hypothesis));
    bundle.files.push_back(generateControl(hypothesis));
    bundle.files.push_back(generateBuildScript(hypothesis));
    bundle.files.push_back(generateMakefile());
    bundle.files.push_back(generateReadme(hypothesis));
    bundle.files.push_back(generateHypothesisJson(hypothesis));
    bundle.files.push_back(generateAnalyze(hypothesis));
    bundle.files.push_back(generateRunAll(hypothesis, plan));

    for (const auto &script : plan.scripts) {
        bundle.files.push_back({"scripts/" + script.name, script.content});
    }

    return bundle;
}

bool ExperimentSynthesizer::writeToDisk(const ExperimentBundle &bundle) {
    for (const auto &file : bundle.files) {
        llvm::SmallString<256> fullPath(bundle.outputDir);
        llvm::sys::path::append(fullPath, file.relativePath);

        llvm::SmallString<256> parentDir = fullPath;
        llvm::sys::path::remove_filename(parentDir);
        if (auto ec = llvm::sys::fs::create_directories(parentDir))
            return false;

        std::error_code EC;
        llvm::raw_fd_ostream out(fullPath, EC, llvm::sys::fs::OF_Text);
        if (EC)
            return false;
        out << file.content;
    }
    return true;
}

} // namespace lshaz
