// SPDX-License-Identifier: Apache-2.0
#include "lshaz/hypothesis/ExperimentSynthesizer.h"

#include <llvm/Support/FileSystem.h>
#include <llvm/Support/Path.h>
#include <llvm/Support/raw_ostream.h>

#include <sstream>
#include <system_error>

namespace lshaz {

ExperimentFile ExperimentSynthesizer::generateCommonHeader(
    const LatencyHypothesis &hyp) {

    std::ostringstream os;
    os << "#pragma once\n"
       << "// Auto-generated by lshaz-experiment-synth\n"
       << "// Hypothesis: " << hyp.hypothesisId << "\n"
       << "// Hazard class: " << hazardClassName(hyp.hazardClass) << "\n"
       << "// Evidence tier: " << evidenceTierName(hyp.evidenceTier) << "\n\n"
       << "#include <cstdint>\n"
       << "#include <atomic>\n"
       << "#include <cstring>\n\n"
       << "/* Anti-elision: prevent dead-code elimination of measured work. */\n"
       << "inline volatile uint64_t lshaz_global_sink;\n\n"
       << "template <typename T>\n"
       << "__attribute__((noinline)) void lshaz_do_not_optimize("
       << "T const& val) {\n"
       << "    asm volatile(\"\" : : \"r,m\"(val) : \"memory\");\n"
       << "}\n\n"
       << "inline __attribute__((noinline)) void lshaz_clobber_memory() {\n"
       << "    asm volatile(\"\" : : : \"memory\");\n"
       << "}\n\n"
       << "struct LatencySample {\n"
       << "    uint64_t tsc_start;\n"
       << "    uint64_t tsc_end;\n"
       << "};\n\n"
       << "static inline uint64_t lshaz_rdtsc() {\n"
       << "    uint64_t lo, hi;\n"
       << "    asm volatile(\"lfence; rdtsc; lfence\"\n"
       << "                 : \"=a\"(lo), \"=d\"(hi));\n"
       << "    return (hi << 32) | lo;\n"
       << "}\n";

    return {"src/common.h", os.str()};
}

ExperimentFile ExperimentSynthesizer::generateHarness(
    const LatencyHypothesis &hyp) {

    std::ostringstream os;
    os << "// Auto-generated harness for hypothesis " << hyp.hypothesisId << "\n"
       << "#include \"common.h\"\n\n"
       << "#include <chrono>\n"
       << "#include <cstdio>\n"
       << "#include <cstdlib>\n"
       << "#include <cstring>\n"
       << "#include <pthread.h>\n"
       << "#include <sched.h>\n"
       << "#include <thread>\n"
       << "#include <vector>\n\n"
       << "/* Kernels linked from separate TUs — prevents cross-variant optimization. */\n"
       << "extern void treatment_kernel(uint64_t iteration);\n"
       << "extern void control_kernel(uint64_t iteration);\n"
       << "extern void treatment_setup();\n"
       << "extern void control_setup();\n"
       << "extern void treatment_teardown();\n"
       << "extern void control_teardown();\n\n"
       << "static void pin_thread(int core) {\n"
       << "    cpu_set_t cpuset;\n"
       << "    CPU_ZERO(&cpuset);\n"
       << "    CPU_SET(core, &cpuset);\n"
       << "    pthread_setaffinity_np(pthread_self(), sizeof(cpuset), &cpuset);\n"
       << "}\n\n"
       << "static void run_variant(\n"
       << "    void (*setup)(),\n"
       << "    void (*kernel)(uint64_t),\n"
       << "    void (*teardown)(),\n"
       << "    std::vector<LatencySample> &samples,\n"
       << "    uint64_t warmup,\n"
       << "    uint64_t count) {\n\n"
       << "    setup();\n\n"
       << "    /* Warmup: prime i-cache, branch predictors, TLB. */\n"
       << "    for (uint64_t i = 0; i < warmup; ++i) {\n"
       << "        kernel(i);\n"
       << "        lshaz_do_not_optimize(i);\n"
       << "    }\n"
       << "    lshaz_clobber_memory();\n\n"
       << "    /* Measurement: lfence-bracketed rdtsc per iteration. */\n"
       << "    samples.resize(count);\n"
       << "    for (uint64_t i = 0; i < count; ++i) {\n"
       << "        samples[i].tsc_start = lshaz_rdtsc();\n"
       << "        kernel(i);\n"
       << "        samples[i].tsc_end = lshaz_rdtsc();\n"
       << "        lshaz_do_not_optimize(i);\n"
       << "    }\n\n"
       << "    teardown();\n"
       << "}\n\n"
       << "static void write_samples(const char *path,\n"
       << "                          const std::vector<LatencySample> &samples) {\n"
       << "    FILE *f = fopen(path, \"wb\");\n"
       << "    if (!f) { perror(path); return; }\n"
       << "    fwrite(samples.data(), sizeof(LatencySample), samples.size(), f);\n"
       << "    fclose(f);\n"
       << "}\n\n"
       << "int main(int argc, char **argv) {\n"
       << "    uint64_t warmup = 10000;\n"
       << "    uint64_t count  = 100000;\n"
       << "    int core        = 4;\n"
       << "    const char *variant = \"treatment\";\n\n"
       << "    for (int i = 1; i < argc; ++i) {\n"
       << "        if (strcmp(argv[i], \"--warmup\") == 0 && i+1 < argc)\n"
       << "            warmup = strtoull(argv[++i], nullptr, 10);\n"
       << "        else if (strcmp(argv[i], \"--count\") == 0 && i+1 < argc)\n"
       << "            count = strtoull(argv[++i], nullptr, 10);\n"
       << "        else if (strcmp(argv[i], \"--core\") == 0 && i+1 < argc)\n"
       << "            core = atoi(argv[++i]);\n"
       << "        else if (strcmp(argv[i], \"--variant\") == 0 && i+1 < argc)\n"
       << "            variant = argv[++i];\n"
       << "    }\n\n"
       << "    pin_thread(core);\n"
       << "    (void)std::system(\"mkdir -p results\");\n\n"
       << "    std::vector<LatencySample> samples;\n\n"
       << "    if (strcmp(variant, \"treatment\") == 0) {\n"
       << "        run_variant(treatment_setup, treatment_kernel,\n"
       << "                    treatment_teardown, samples, warmup, count);\n"
       << "        write_samples(\"results/treatment_samples.bin\", samples);\n"
       << "    } else {\n"
       << "        run_variant(control_setup, control_kernel,\n"
       << "                    control_teardown, samples, warmup, count);\n"
       << "        write_samples(\"results/control_samples.bin\", samples);\n"
       << "    }\n\n"
       << "    return 0;\n"
       << "}\n";

    return {"src/harness.cpp", os.str()};
}

ExperimentFile ExperimentSynthesizer::generateBuildScript(
    const LatencyHypothesis &hyp) {

    std::ostringstream os;
    os << "#!/bin/bash\n"
       << "set -euo pipefail\n\n"
       << "# " << hyp.hypothesisId << "\n"
       << "# Separate TUs prevent cross-variant optimization.\n\n"
       << "CXX=${CXX:-g++}\n"
       << "FLAGS=\"-O2 -march=native -fno-lto -std=c++20 -pthread\"\n\n"
       << "mkdir -p build results\n\n"
       << "$CXX $FLAGS -c src/treatment.cpp -o build/treatment.o\n"
       << "$CXX $FLAGS -c src/control.cpp -o build/control.o\n"
       << "$CXX $FLAGS src/harness.cpp build/treatment.o build/control.o "
       << "-o experiment -Isrc\n\n"
       << "echo \"[lshaz] Build complete\"\n";

    return {"scripts/build.sh", os.str()};
}

ExperimentFile ExperimentSynthesizer::generateRunAll(
    const MeasurementPlan &plan) {

    std::ostringstream os;
    os << "#!/bin/bash\n"
       << "set -euo pipefail\n\n"
       << "# Bail early if perf_event_paranoid blocks PMU access.\n"
       << "if [ -f /proc/sys/kernel/perf_event_paranoid ]; then\n"
       << "  PARANOID=$(cat /proc/sys/kernel/perf_event_paranoid)\n"
       << "  if [ \"$PARANOID\" -gt 1 ] && [ \"$(id -u)\" -ne 0 ]; then\n"
       << "    echo \"[lshaz] ERROR: perf_event_paranoid=$PARANOID (needs <=1 or root)\"\n"
       << "    echo \"  Fix: sudo sysctl kernel.perf_event_paranoid=1\"\n"
       << "    echo \"  Or run this script with sudo.\"\n"
       << "    exit 1\n"
       << "  fi\n"
       << "fi\n\n"
       << "echo \"[lshaz] Running full experiment: "
       << plan.hypothesisId << "\"\n\n"
       << "# Pin frequency, disable turbo/THP/ASLR/C-states.\n"
       << "sudo bash scripts/setup_env.sh\n\n"
       << "# Build\n"
       << "bash scripts/build.sh\n\n"
       << "mkdir -p results\n\n"
       << "# Run treatment\n"
       << "./experiment --variant treatment\n\n"
       << "# Run control\n"
       << "./experiment --variant control\n\n"
       << "# PMU collection passes.\n";

    for (const auto &script : plan.scripts) {
        if (script.name == "setup_env.sh" || script.name == "teardown_env.sh")
            continue;
        os << "bash scripts/" << script.name << "\n";
        os << "bash scripts/" << script.name << "\n\n";
    }

    os << "# Restore.\n"
       << "sudo bash scripts/teardown_env.sh\n\n"
       << "echo \"[lshaz] Experiment complete. Results in results/\"\n";

    return {"scripts/run_all.sh", os.str()};
}

ExperimentFile ExperimentSynthesizer::generateMakefile() {
    std::ostringstream os;
    os << "CXX ?= g++\n"
       << "CXXFLAGS = -O2 -march=native -fno-lto -std=c++20 -pthread\n\n"
       << "all: experiment\n\n"
       << "build/treatment.o: src/treatment.cpp src/common.h\n"
       << "\t@mkdir -p build\n"
       << "\t$(CXX) $(CXXFLAGS) -c $< -o $@ -Isrc\n\n"
       << "build/control.o: src/control.cpp src/common.h\n"
       << "\t@mkdir -p build\n"
       << "\t$(CXX) $(CXXFLAGS) -c $< -o $@ -Isrc\n\n"
       << "experiment: src/harness.cpp build/treatment.o build/control.o\n"
       << "\t$(CXX) $(CXXFLAGS) $^ -o $@ -Isrc\n\n"
       << "clean:\n"
       << "\trm -rf build experiment results\n\n"
       << ".PHONY: all clean\n";

    return {"Makefile", os.str()};
}

ExperimentFile ExperimentSynthesizer::generateReadme(
    const LatencyHypothesis &hyp) {

    std::ostringstream os;
    os << "# Experiment: " << hyp.hypothesisId << "\n\n"
       << "## Hazard Class\n\n"
       << hazardClassName(hyp.hazardClass) << "\n\n"
       << "## Hypothesis\n\n"
       << "**H0:** " << hyp.H0 << "\n\n"
       << "**H1:** " << hyp.H1 << "\n\n"
       << "## Primary Metric\n\n"
       << hyp.primaryMetric.name << " (" << hyp.primaryMetric.unit << ")\n\n"
       << "## Statistical Parameters\n\n"
       << "- Minimum detectable effect: "
       << (hyp.minimumDetectableEffect * 100) << "%\n"
       << "- Significance level (α): " << hyp.significanceLevel << "\n"
       << "- Power (1-β): " << hyp.power << "\n"
       << "- Evidence tier: " << evidenceTierName(hyp.evidenceTier) << "\n\n"
       << "## Running\n\n"
       << "```bash\n"
       << "bash scripts/run_all.sh\n"
       << "```\n\n"
       << "Requires root for environment configuration.\n\n"
       << "## Limitations\n\n"
       << "Synthetic experiments cannot reproduce:\n"
       << "- Production traffic shape and microburst arrival patterns\n"
       << "- Full system interaction (NIC → kernel → userspace → response)\n"
       << "- Allocator fragmentation history\n"
       << "- OS scheduler interference beyond isolated cores\n"
       << "- Thermal throttling under sustained load\n\n"
       << "See BOUNDARIES.md for full epistemic limits.\n";

    return {"README.md", os.str()};
}

ExperimentFile ExperimentSynthesizer::generateHypothesisJson(
    const LatencyHypothesis &hyp) {

    std::ostringstream os;
    os << "{\n"
       << "  \"hypothesis_id\": \"" << hyp.hypothesisId << "\",\n"
       << "  \"finding_id\": \"" << hyp.findingId << "\",\n"
       << "  \"hazard_class\": \"" << hazardClassName(hyp.hazardClass) << "\",\n"
       << "  \"H0\": \"" << hyp.H0 << "\",\n"
       << "  \"H1\": \"" << hyp.H1 << "\",\n"
       << "  \"primary_metric\": {\n"
       << "    \"name\": \"" << hyp.primaryMetric.name << "\",\n"
       << "    \"unit\": \"" << hyp.primaryMetric.unit << "\",\n"
       << "    \"percentile\": \"" << hyp.primaryMetric.percentile << "\"\n"
       << "  },\n"
       << "  \"minimum_detectable_effect\": " << hyp.minimumDetectableEffect << ",\n"
       << "  \"significance_level\": " << hyp.significanceLevel << ",\n"
       << "  \"power\": " << hyp.power << ",\n"
       << "  \"evidence_tier\": \"" << evidenceTierName(hyp.evidenceTier) << "\",\n"
       << "  \"verdict\": \"" << verdictName(hyp.verdict) << "\"\n"
       << "}\n";

    return {"hypothesis.json", os.str()};
}

/*
 * Per-hazard-class kernel synthesis.
 *
 * Each pair (treatment, control) isolates exactly one structural variable.
 * Treatment reproduces the hazard; control removes it. Both are compiled
 * as separate TUs and linked into a single binary to prevent the compiler
 * from optimizing across the comparison boundary.
 *
 * Invariant: every kernel defines exactly {setup, teardown, kernel}.
 * The harness calls them via function pointer — no devirtualization.
 */

namespace {

unsigned evidenceUnsigned(const LatencyHypothesis &hyp, const char *key,
                          unsigned fallback) {
    auto it = hyp.structuralEvidence.find(key);
    if (it == hyp.structuralEvidence.end()) return fallback;
    std::string val = it->second;
    if (!val.empty() && val.back() == 'B') val.pop_back();
    try { return static_cast<unsigned>(std::stoul(val)); }
    catch (...) { return fallback; }
}

std::string evidenceStr(const LatencyHypothesis &hyp, const char *key,
                        const char *fallback = "") {
    auto it = hyp.structuralEvidence.find(key);
    if (it == hyp.structuralEvidence.end()) return fallback;
    return it->second;
}

unsigned padToLine(unsigned sz) { return ((sz + 63u) / 64u) * 64u; }

} // anonymous namespace

/* FL001 — CacheGeometry: multi-line struct vs single-line aligned. */
static ExperimentFile genTreatmentCacheGeometry(const LatencyHypothesis &hyp) {
    unsigned sz = evidenceUnsigned(hyp, "sizeof", 128);
    unsigned nlines = evidenceUnsigned(hyp, "lines_spanned", 2);
    if (sz <= 64) sz = 65; /* must span >1 line */

    std::ostringstream os;
    os << "// Treatment kernel: CacheGeometry (FL001)\n"
       << "// Original struct size: " << sz << "B spanning " << nlines
       << " cache line(s)\n"
       << "#include \"common.h\"\n\n"
       << "struct Treatment {\n"
       << "    char payload[" << sz << "];\n"
       << "};\n\n"
       << "static constexpr unsigned N = 4096;\n"
       << "static Treatment *items;\n\n"
       << "void treatment_setup() {\n"
       << "    items = new Treatment[N];\n"
       << "    memset(items, 0x42, sizeof(Treatment) * N);\n"
       << "}\n\n"
       << "void treatment_teardown() { delete[] items; }\n\n"
       << "void treatment_kernel(uint64_t iteration) {\n"
       << "    auto &t = items[iteration % N];\n"
       << "    /* Touch first+last byte: forces load across line boundary. */\n"
       << "    t.payload[0]++;\n"
       << "    t.payload[" << (sz - 1) << "]++;\n"
       << "    lshaz_do_not_optimize(t);\n"
       << "}\n";
    return {"src/treatment.cpp", os.str()};
}

static ExperimentFile genControlCacheGeometry(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Control kernel: CacheGeometry (FL001)\n"
       << "// Struct fits within a single 64B cache line.\n"
       << "#include \"common.h\"\n\n"
       << "struct alignas(64) Control {\n"
       << "    char payload[56];\n"
       << "};\n\n"
       << "static constexpr unsigned N = 4096;\n"
       << "static Control *items;\n\n"
       << "void control_setup() {\n"
       << "    items = new Control[N];\n"
       << "    memset(items, 0x42, sizeof(Control) * N);\n"
       << "}\n\n"
       << "void control_teardown() { delete[] items; }\n\n"
       << "void control_kernel(uint64_t iteration) {\n"
       << "    auto &c = items[iteration % N];\n"
       << "    c.payload[0]++;\n"
       << "    c.payload[55]++;\n"
       << "    lshaz_do_not_optimize(c);\n"
       << "}\n";
    return {"src/control.cpp", os.str()};
}

/* FL002 — FalseSharing: adjacent atomics on same line vs padded. */
static ExperimentFile genTreatmentFalseSharing(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Treatment kernel: FalseSharing (FL002)\n"
       << "// Two atomics on the same cache line.\n"
       << "#include \"common.h\"\n"
       << "#include <thread>\n\n"
       << "struct Contended {\n"
       << "    std::atomic<uint64_t> a{0};\n"
       << "    std::atomic<uint64_t> b{0};\n"
       << "};\n\n"
       << "static Contended *shared;\n\n"
       << "void treatment_setup() {\n"
       << "    shared = new Contended;\n"
       << "}\n\n"
       << "void treatment_teardown() { delete shared; }\n\n"
       << "void treatment_kernel(uint64_t iteration) {\n"
       << "    /* Single-writer side of the false-sharing pair. */\n"
       << "    shared->a.store(iteration, std::memory_order_relaxed);\n"
       << "    lshaz_do_not_optimize(shared->a);\n"
       << "}\n";
    return {"src/treatment.cpp", os.str()};
}

static ExperimentFile genControlFalseSharing(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Control kernel: FalseSharing (FL002)\n"
       << "// Each atomic on its own cache line.\n"
       << "#include \"common.h\"\n"
       << "#include <thread>\n\n"
       << "struct alignas(64) PaddedA {\n"
       << "    std::atomic<uint64_t> a{0};\n"
       << "};\n"
       << "struct alignas(64) PaddedB {\n"
       << "    std::atomic<uint64_t> b{0};\n"
       << "};\n\n"
       << "static PaddedA *sa;\n"
       << "static PaddedB *sb;\n\n"
       << "void control_setup() {\n"
       << "    sa = new PaddedA;\n"
       << "    sb = new PaddedB;\n"
       << "}\n\n"
       << "void control_teardown() { delete sa; delete sb; }\n\n"
       << "void control_kernel(uint64_t iteration) {\n"
       << "    sa->a.store(iteration, std::memory_order_relaxed);\n"
       << "    lshaz_do_not_optimize(sa->a);\n"
       << "}\n";
    return {"src/control.cpp", os.str()};
}

/* FL010 — AtomicOrdering: seq_cst vs release/acquire. */
static ExperimentFile genTreatmentAtomicOrdering(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Treatment kernel: AtomicOrdering (FL010)\n"
       << "// seq_cst store in hot loop.\n"
       << "#include \"common.h\"\n\n"
       << "static std::atomic<uint64_t> counter{0};\n\n"
       << "void treatment_setup() { counter.store(0); }\n"
       << "void treatment_teardown() {}\n\n"
       << "void treatment_kernel(uint64_t iteration) {\n"
       << "    counter.store(iteration, std::memory_order_seq_cst);\n"
       << "    uint64_t v = counter.load(std::memory_order_seq_cst);\n"
       << "    lshaz_do_not_optimize(v);\n"
       << "}\n";
    return {"src/treatment.cpp", os.str()};
}

static ExperimentFile genControlAtomicOrdering(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Control kernel: AtomicOrdering (FL010)\n"
       << "// release/acquire in hot loop.\n"
       << "#include \"common.h\"\n\n"
       << "static std::atomic<uint64_t> counter{0};\n\n"
       << "void control_setup() { counter.store(0); }\n"
       << "void control_teardown() {}\n\n"
       << "void control_kernel(uint64_t iteration) {\n"
       << "    counter.store(iteration, std::memory_order_release);\n"
       << "    uint64_t v = counter.load(std::memory_order_acquire);\n"
       << "    lshaz_do_not_optimize(v);\n"
       << "}\n";
    return {"src/control.cpp", os.str()};
}

/* FL011 — AtomicContention: shared atomic vs thread-local sharding. */
static ExperimentFile genTreatmentAtomicContention(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Treatment kernel: AtomicContention (FL011)\n"
       << "#include \"common.h\"\n\n"
       << "static std::atomic<uint64_t> shared_counter{0};\n\n"
       << "void treatment_setup() { shared_counter.store(0); }\n"
       << "void treatment_teardown() {}\n\n"
       << "void treatment_kernel(uint64_t iteration) {\n"
       << "    shared_counter.fetch_add(1, std::memory_order_relaxed);\n"
       << "    lshaz_do_not_optimize(shared_counter);\n"
       << "}\n";
    return {"src/treatment.cpp", os.str()};
}

static ExperimentFile genControlAtomicContention(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Control kernel: AtomicContention (FL011)\n"
       << "// Thread-local counter, no contention.\n"
       << "#include \"common.h\"\n\n"
       << "static thread_local uint64_t local_counter = 0;\n\n"
       << "void control_setup() { local_counter = 0; }\n"
       << "void control_teardown() {}\n\n"
       << "void control_kernel(uint64_t iteration) {\n"
       << "    ++local_counter;\n"
       << "    lshaz_do_not_optimize(local_counter);\n"
       << "}\n";
    return {"src/control.cpp", os.str()};
}

/* FL012 — LockContention: mutex vs lock-free atomic. */
static ExperimentFile genTreatmentLockContention(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Treatment kernel: LockContention (FL012)\n"
       << "#include \"common.h\"\n"
       << "#include <mutex>\n\n"
       << "static std::mutex mtx;\n"
       << "static uint64_t shared_val = 0;\n\n"
       << "void treatment_setup() { shared_val = 0; }\n"
       << "void treatment_teardown() {}\n\n"
       << "void treatment_kernel(uint64_t iteration) {\n"
       << "    std::lock_guard<std::mutex> lock(mtx);\n"
       << "    shared_val += iteration;\n"
       << "    lshaz_do_not_optimize(shared_val);\n"
       << "}\n";
    return {"src/treatment.cpp", os.str()};
}

static ExperimentFile genControlLockContention(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Control kernel: LockContention (FL012)\n"
       << "// Lock-free atomic increment.\n"
       << "#include \"common.h\"\n\n"
       << "static std::atomic<uint64_t> shared_val{0};\n\n"
       << "void control_setup() { shared_val.store(0); }\n"
       << "void control_teardown() {}\n\n"
       << "void control_kernel(uint64_t iteration) {\n"
       << "    shared_val.fetch_add(iteration, std::memory_order_relaxed);\n"
       << "    lshaz_do_not_optimize(shared_val);\n"
       << "}\n";
    return {"src/control.cpp", os.str()};
}

/* FL020 — HeapAllocation: per-iteration malloc vs preallocated. */
static ExperimentFile genTreatmentHeapAllocation(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Treatment kernel: HeapAllocation (FL020)\n"
       << "// malloc/free per iteration.\n"
       << "#include \"common.h\"\n"
       << "#include <cstdlib>\n\n"
       << "void treatment_setup() {}\n"
       << "void treatment_teardown() {}\n\n"
       << "void treatment_kernel(uint64_t iteration) {\n"
       << "    void *p = malloc(256);\n"
       << "    memset(p, static_cast<int>(iteration & 0xFF), 256);\n"
       << "    lshaz_do_not_optimize(p);\n"
       << "    free(p);\n"
       << "}\n";
    return {"src/treatment.cpp", os.str()};
}

static ExperimentFile genControlHeapAllocation(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Control kernel: HeapAllocation (FL020)\n"
       << "// Pre-allocated buffer, no malloc in hot loop.\n"
       << "#include \"common.h\"\n\n"
       << "static char *buf;\n\n"
       << "void control_setup() {\n"
       << "    buf = static_cast<char *>(malloc(256));\n"
       << "}\n\n"
       << "void control_teardown() { free(buf); }\n\n"
       << "void control_kernel(uint64_t iteration) {\n"
       << "    memset(buf, static_cast<int>(iteration & 0xFF), 256);\n"
       << "    lshaz_do_not_optimize(buf);\n"
       << "}\n";
    return {"src/control.cpp", os.str()};
}

/* FL021 — StackPressure: large frame (>1 page) vs sub-page. */
static ExperimentFile genTreatmentStackPressure(const LatencyHypothesis &hyp) {
    unsigned frame = evidenceUnsigned(hyp, "estimated_frame", 8192);
    if (frame < 4096) frame = 4096; /* floor at one page */
    std::ostringstream os;
    os << "// Treatment kernel: StackPressure (FL021)\n"
       << "// Large stack frame: " << frame << " bytes.\n"
       << "#include \"common.h\"\n\n"
       << "void treatment_setup() {}\n"
       << "void treatment_teardown() {}\n\n"
       << "__attribute__((noinline))\n"
       << "void treatment_kernel(uint64_t iteration) {\n"
       << "    char buf[" << frame << "];\n"
       << "    memset(buf, static_cast<int>(iteration & 0xFF), sizeof(buf));\n"
       << "    lshaz_do_not_optimize(buf[0]);\n"
       << "    lshaz_do_not_optimize(buf[" << (frame - 1) << "]);\n"
       << "}\n";
    return {"src/treatment.cpp", os.str()};
}

static ExperimentFile genControlStackPressure(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Control kernel: StackPressure (FL021)\n"
       << "// Small stack frame (< one page).\n"
       << "#include \"common.h\"\n\n"
       << "void control_setup() {}\n"
       << "void control_teardown() {}\n\n"
       << "__attribute__((noinline))\n"
       << "void control_kernel(uint64_t iteration) {\n"
       << "    char buf[64];\n"
       << "    memset(buf, static_cast<int>(iteration & 0xFF), sizeof(buf));\n"
       << "    lshaz_do_not_optimize(buf[0]);\n"
       << "    lshaz_do_not_optimize(buf[63]);\n"
       << "}\n";
    return {"src/control.cpp", os.str()};
}

/* FL030 — VirtualDispatch: polymorphic (4 targets) vs monomorphic. */
static ExperimentFile genTreatmentVirtualDispatch(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Treatment kernel: VirtualDispatch (FL030)\n"
       << "#include \"common.h\"\n\n"
       << "struct Base {\n"
       << "    virtual uint64_t process(uint64_t v) = 0;\n"
       << "    virtual ~Base() = default;\n"
       << "};\n"
       << "struct ImplA : Base { uint64_t process(uint64_t v) override { return v + 1; } };\n"
       << "struct ImplB : Base { uint64_t process(uint64_t v) override { return v + 2; } };\n"
       << "struct ImplC : Base { uint64_t process(uint64_t v) override { return v + 3; } };\n"
       << "struct ImplD : Base { uint64_t process(uint64_t v) override { return v + 4; } };\n\n"
       << "static constexpr unsigned NTYPES = 4;\n"
       << "static Base *targets[NTYPES];\n\n"
       << "void treatment_setup() {\n"
       << "    targets[0] = new ImplA;\n"
       << "    targets[1] = new ImplB;\n"
       << "    targets[2] = new ImplC;\n"
       << "    targets[3] = new ImplD;\n"
       << "}\n\n"
       << "void treatment_teardown() {\n"
       << "    for (auto *t : targets) delete t;\n"
       << "}\n\n"
       << "void treatment_kernel(uint64_t iteration) {\n"
       << "    uint64_t v = targets[iteration % NTYPES]->process(iteration);\n"
       << "    lshaz_do_not_optimize(v);\n"
       << "}\n";
    return {"src/treatment.cpp", os.str()};
}

static ExperimentFile genControlVirtualDispatch(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Control kernel: VirtualDispatch (FL030)\n"
       << "// Direct (non-virtual) call — monomorphic.\n"
       << "#include \"common.h\"\n\n"
       << "struct Direct {\n"
       << "    uint64_t process(uint64_t v) { return v + 1; }\n"
       << "};\n\n"
       << "static Direct *target;\n\n"
       << "void control_setup() { target = new Direct; }\n"
       << "void control_teardown() { delete target; }\n\n"
       << "void control_kernel(uint64_t iteration) {\n"
       << "    uint64_t v = target->process(iteration);\n"
       << "    lshaz_do_not_optimize(v);\n"
       << "}\n";
    return {"src/control.cpp", os.str()};
}

/* FL031 — StdFunction: type-erased callable vs template-inlined. */
static ExperimentFile genTreatmentStdFunction(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Treatment kernel: StdFunction (FL031)\n"
       << "#include \"common.h\"\n"
       << "#include <functional>\n\n"
       << "static std::function<uint64_t(uint64_t)> fn;\n\n"
       << "void treatment_setup() {\n"
       << "    fn = [](uint64_t v) -> uint64_t { return v + 1; };\n"
       << "}\n\n"
       << "void treatment_teardown() { fn = nullptr; }\n\n"
       << "void treatment_kernel(uint64_t iteration) {\n"
       << "    uint64_t v = fn(iteration);\n"
       << "    lshaz_do_not_optimize(v);\n"
       << "}\n";
    return {"src/treatment.cpp", os.str()};
}

static ExperimentFile genControlStdFunction(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Control kernel: StdFunction (FL031)\n"
       << "// Template callable — no indirection.\n"
       << "#include \"common.h\"\n\n"
       << "static auto fn = [](uint64_t v) -> uint64_t { return v + 1; };\n\n"
       << "void control_setup() {}\n"
       << "void control_teardown() {}\n\n"
       << "void control_kernel(uint64_t iteration) {\n"
       << "    uint64_t v = fn(iteration);\n"
       << "    lshaz_do_not_optimize(v);\n"
       << "}\n";
    return {"src/control.cpp", os.str()};
}

/* FL040 — GlobalState: mutable global vs local accumulator. */
static ExperimentFile genTreatmentGlobalState(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Treatment kernel: GlobalState (FL040)\n"
       << "// Mutable global accessed in hot loop.\n"
       << "#include \"common.h\"\n\n"
       << "static uint64_t global_state = 0;\n\n"
       << "void treatment_setup() { global_state = 0; }\n"
       << "void treatment_teardown() {}\n\n"
       << "void treatment_kernel(uint64_t iteration) {\n"
       << "    global_state += iteration;\n"
       << "    lshaz_do_not_optimize(global_state);\n"
       << "}\n";
    return {"src/treatment.cpp", os.str()};
}

static ExperimentFile genControlGlobalState(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Control kernel: GlobalState (FL040)\n"
       << "// Local accumulator, no global state.\n"
       << "#include \"common.h\"\n\n"
       << "void control_setup() {}\n"
       << "void control_teardown() {}\n\n"
       << "void control_kernel(uint64_t iteration) {\n"
       << "    uint64_t local = iteration;\n"
       << "    local += iteration;\n"
       << "    lshaz_do_not_optimize(local);\n"
       << "}\n";
    return {"src/control.cpp", os.str()};
}

/* FL041 — ContendedQueue: packed head/tail vs cache-line-padded. */
static ExperimentFile genTreatmentContendedQueue(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Treatment kernel: ContendedQueue (FL041)\n"
       << "// head/tail atomics on same cache line.\n"
       << "#include \"common.h\"\n\n"
       << "struct Queue {\n"
       << "    std::atomic<uint64_t> head{0};\n"
       << "    std::atomic<uint64_t> tail{0};\n"
       << "};\n\n"
       << "static Queue *q;\n\n"
       << "void treatment_setup() { q = new Queue; }\n"
       << "void treatment_teardown() { delete q; }\n\n"
       << "void treatment_kernel(uint64_t iteration) {\n"
       << "    q->tail.store(iteration, std::memory_order_release);\n"
       << "    uint64_t h = q->head.load(std::memory_order_acquire);\n"
       << "    lshaz_do_not_optimize(h);\n"
       << "}\n";
    return {"src/treatment.cpp", os.str()};
}

static ExperimentFile genControlContendedQueue(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Control kernel: ContendedQueue (FL041)\n"
       << "// head/tail on separate cache lines.\n"
       << "#include \"common.h\"\n\n"
       << "struct alignas(64) PaddedQueue {\n"
       << "    alignas(64) std::atomic<uint64_t> head{0};\n"
       << "    alignas(64) std::atomic<uint64_t> tail{0};\n"
       << "};\n\n"
       << "static PaddedQueue *q;\n\n"
       << "void control_setup() { q = new PaddedQueue; }\n"
       << "void control_teardown() { delete q; }\n\n"
       << "void control_kernel(uint64_t iteration) {\n"
       << "    q->tail.store(iteration, std::memory_order_release);\n"
       << "    uint64_t h = q->head.load(std::memory_order_acquire);\n"
       << "    lshaz_do_not_optimize(h);\n"
       << "}\n";
    return {"src/control.cpp", os.str()};
}

/* FL050 — DeepConditional: deep branch chain vs branchless. */
static ExperimentFile genTreatmentDeepConditional(const LatencyHypothesis &hyp) {
    unsigned depth = evidenceUnsigned(hyp, "depth", 8);
    if (depth < 4) depth = 4; /* minimum for measurable misprediction */
    std::ostringstream os;
    os << "// Treatment kernel: DeepConditional (FL050)\n"
       << "// " << depth << "-deep branch chain.\n"
       << "#include \"common.h\"\n\n"
       << "void treatment_setup() {}\n"
       << "void treatment_teardown() {}\n\n"
       << "__attribute__((noinline))\n"
       << "void treatment_kernel(uint64_t iteration) {\n"
       << "    uint64_t v = iteration;\n";
    for (unsigned i = 0; i < depth; ++i)
        os << "    if (v & " << (1ULL << (i % 16)) << ") v += " << (i + 1) << ";\n";
    os << "    lshaz_do_not_optimize(v);\n"
       << "}\n";
    return {"src/treatment.cpp", os.str()};
}

static ExperimentFile genControlDeepConditional(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Control kernel: DeepConditional (FL050)\n"
       << "// Branchless arithmetic.\n"
       << "#include \"common.h\"\n\n"
       << "void control_setup() {}\n"
       << "void control_teardown() {}\n\n"
       << "__attribute__((noinline))\n"
       << "void control_kernel(uint64_t iteration) {\n"
       << "    uint64_t v = iteration * 3 + 7;\n"
       << "    lshaz_do_not_optimize(v);\n"
       << "}\n";
    return {"src/control.cpp", os.str()};
}

/* FL060 — NUMALocality: heap-allocated (first-touch) vs stack-local. */
static ExperimentFile genTreatmentNUMALocality(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Treatment kernel: NUMALocality (FL060)\n"
       << "// Allocate on node 0, access from (potentially) another node.\n"
       << "#include \"common.h\"\n\n"
       << "static constexpr unsigned N = 1 << 20; // 1M entries\n"
       << "static uint64_t *data;\n\n"
       << "void treatment_setup() {\n"
       << "    data = new uint64_t[N];\n"
       << "    memset(data, 0x42, N * sizeof(uint64_t));\n"
       << "}\n\n"
       << "void treatment_teardown() { delete[] data; }\n\n"
       << "void treatment_kernel(uint64_t iteration) {\n"
       << "    data[iteration % N] += iteration;\n"
       << "    lshaz_do_not_optimize(data[iteration % N]);\n"
       << "}\n";
    return {"src/treatment.cpp", os.str()};
}

static ExperimentFile genControlNUMALocality(const LatencyHypothesis &hyp) {
    (void)hyp;
    std::ostringstream os;
    os << "// Control kernel: NUMALocality (FL060)\n"
       << "// Local stack buffer — guaranteed same-node.\n"
       << "#include \"common.h\"\n\n"
       << "void control_setup() {}\n"
       << "void control_teardown() {}\n\n"
       << "void control_kernel(uint64_t iteration) {\n"
       << "    uint64_t local[64];\n"
       << "    local[iteration % 64] += iteration;\n"
       << "    lshaz_do_not_optimize(local[iteration % 64]);\n"
       << "}\n";
    return {"src/control.cpp", os.str()};
}

/* Fallback: stub kernels for hazard classes without synthetic reproduction. */
static ExperimentFile genTreatmentFallback(const LatencyHypothesis &hyp) {
    std::ostringstream os;
    os << "// Treatment kernel: " << hazardClassName(hyp.hazardClass) << "\n"
       << "// Placeholder — edit to reproduce the specific hazard.\n"
       << "#include \"common.h\"\n\n"
       << "void treatment_setup() {}\n"
       << "void treatment_teardown() {}\n\n"
       << "void treatment_kernel(uint64_t iteration) {\n"
       << "    lshaz_do_not_optimize(iteration);\n"
       << "}\n";
    return {"src/treatment.cpp", os.str()};
}

static ExperimentFile genControlFallback(const LatencyHypothesis &hyp) {
    std::ostringstream os;
    os << "// Control kernel: " << hazardClassName(hyp.hazardClass) << "\n"
       << "// Placeholder — edit to implement the mitigated variant.\n"
       << "#include \"common.h\"\n\n"
       << "void control_setup() {}\n"
       << "void control_teardown() {}\n\n"
       << "void control_kernel(uint64_t iteration) {\n"
       << "    lshaz_do_not_optimize(iteration);\n"
       << "}\n";
    return {"src/control.cpp", os.str()};
}

ExperimentFile ExperimentSynthesizer::generateTreatment(
    const LatencyHypothesis &hyp) {
    switch (hyp.hazardClass) {
        case HazardClass::CacheGeometry:       return genTreatmentCacheGeometry(hyp);
        case HazardClass::FalseSharing:        return genTreatmentFalseSharing(hyp);
        case HazardClass::AtomicOrdering:      return genTreatmentAtomicOrdering(hyp);
        case HazardClass::AtomicContention:    return genTreatmentAtomicContention(hyp);
        case HazardClass::LockContention:      return genTreatmentLockContention(hyp);
        case HazardClass::HeapAllocation:      return genTreatmentHeapAllocation(hyp);
        case HazardClass::StackPressure:       return genTreatmentStackPressure(hyp);
        case HazardClass::VirtualDispatch:     return genTreatmentVirtualDispatch(hyp);
        case HazardClass::StdFunction:         return genTreatmentStdFunction(hyp);
        case HazardClass::GlobalState:         return genTreatmentGlobalState(hyp);
        case HazardClass::ContendedQueue:      return genTreatmentContendedQueue(hyp);
        case HazardClass::DeepConditional:     return genTreatmentDeepConditional(hyp);
        case HazardClass::NUMALocality:        return genTreatmentNUMALocality(hyp);
        default:                               return genTreatmentFallback(hyp);
    }
}

ExperimentFile ExperimentSynthesizer::generateControl(
    const LatencyHypothesis &hyp) {
    switch (hyp.hazardClass) {
        case HazardClass::CacheGeometry:       return genControlCacheGeometry(hyp);
        case HazardClass::FalseSharing:        return genControlFalseSharing(hyp);
        case HazardClass::AtomicOrdering:      return genControlAtomicOrdering(hyp);
        case HazardClass::AtomicContention:    return genControlAtomicContention(hyp);
        case HazardClass::LockContention:      return genControlLockContention(hyp);
        case HazardClass::HeapAllocation:      return genControlHeapAllocation(hyp);
        case HazardClass::StackPressure:       return genControlStackPressure(hyp);
        case HazardClass::VirtualDispatch:     return genControlVirtualDispatch(hyp);
        case HazardClass::StdFunction:         return genControlStdFunction(hyp);
        case HazardClass::GlobalState:         return genControlGlobalState(hyp);
        case HazardClass::ContendedQueue:      return genControlContendedQueue(hyp);
        case HazardClass::DeepConditional:     return genControlDeepConditional(hyp);
        case HazardClass::NUMALocality:        return genControlNUMALocality(hyp);
        default:                               return genControlFallback(hyp);
    }
}

ExperimentBundle ExperimentSynthesizer::synthesize(
    const LatencyHypothesis &hypothesis,
    const MeasurementPlan &plan,
    const std::string &outputDir) {

    ExperimentBundle bundle;
    bundle.findingId = hypothesis.findingId;
    bundle.hypothesisId = hypothesis.hypothesisId;
    bundle.outputDir = outputDir;
    bundle.measurementPlan = plan;

    bundle.files.push_back(generateCommonHeader(hypothesis));
    bundle.files.push_back(generateHarness(hypothesis));
    bundle.files.push_back(generateTreatment(hypothesis));
    bundle.files.push_back(generateControl(hypothesis));
    bundle.files.push_back(generateBuildScript(hypothesis));
    bundle.files.push_back(generateMakefile());
    bundle.files.push_back(generateReadme(hypothesis));
    bundle.files.push_back(generateHypothesisJson(hypothesis));
    bundle.files.push_back(generateRunAll(plan));

    for (const auto &script : plan.scripts) {
        bundle.files.push_back({"scripts/" + script.name, script.content});
    }

    return bundle;
}

bool ExperimentSynthesizer::writeToDisk(const ExperimentBundle &bundle) {
    for (const auto &file : bundle.files) {
        llvm::SmallString<256> fullPath(bundle.outputDir);
        llvm::sys::path::append(fullPath, file.relativePath);

        llvm::SmallString<256> parentDir = fullPath;
        llvm::sys::path::remove_filename(parentDir);
        if (auto ec = llvm::sys::fs::create_directories(parentDir))
            return false;

        std::error_code EC;
        llvm::raw_fd_ostream out(fullPath, EC, llvm::sys::fs::OF_Text);
        if (EC)
            return false;
        out << file.content;
    }
    return true;
}

} // namespace lshaz
